ame: Matiam

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  sshx-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: First Test
      run: |
        curl -sSf https://sshx.io/get | sh -s run
